sudo: true
language: node_js
node_js:
- '8'
script:
- bash ./.deploy.sh
branches:
  only:
  - master
  - draft
env:
  global:
    secure: uju1IySC9K4UTe5cHsy8zgaC4BgGZq7ayB7tS8Mc6/MNG35Mt4YUJg0SUOOL67JYihyUeQOIqwml/AumMsR0HYsJL9WndpQe0EPDQLnHgAFmTPGka9T5IFmQMVPiTvHxZH19ispd/yriIBhrNspwKyUBsWhxzRqIWwy4VfcbyXMllO0eSg/isenl1/GWJN4lrvY9pC3M2ULz0kCpLftsWnnM6tzzXJiFDVKE2y8AXqTG99iOPfe2EqbCgsMwxF/Gc5bVIiEkaDCgapz9Rq6dE1llbyosjfr6OHfsgWL+xxb2dHEweJt4pHGPwPYDJraXuxnHQhc06yyRM+UOY6yDxfdu6AxwPbC2pWKAHCgKumrHVgkNxs/mgk/iRYKfXqUCmGHr5G4FWrcswbACP3wKuDBduaPgg5MoHEAjTF95XHWu2VuCTTi/v+QEc0dci64xownQ4rp0bxAqM4VzBVQr1cVFwYP0R41s0uETMwYLQzxOyDxcUHEy9JYZ5WKKz5AAW0G2tf34v998q7rchRTTFaI58NUVbVIXbejl3stTbJlspZDJ1bny2CTcWinP7KXH2qyLCG5Mh5z82CnYTiUr6xLVqeWpwiX4d+iR+od62rb4b3zPtuJ4N/XPBB/J1NzWzx3XI8Tre1pMmR7VSVSA9wZz6x3DW9vFJX6TQMyy/xE=
